### ISSUE TITLE
Please can we get the latest version pushed to npm?

### ISSUE THREAD

**Issue by diarmidmackenzie** [InfiniteLee/three-to-ammo#39]
I maintain a fork of aframe-physics-system, https://github.com/c-frame/aframe-physics-system

We have a dependency on three-to-ammo, which we pull from npm.

At the next A-Frame release (1.4.0, coming soon), we will need this fix: https://github.com/InfiniteLee/three-to-ammo/commit/501ad4eaa03232806d53d77781ede54ddb582ec6

Would it be possible to publish this to npm, so that we can pull down a version with the fix?

If we don't have this fix, we will hit this error, since Matrix4.getInverse() has finally been removed.

Uncaught TypeError: inverse.getInverse is not a function
    at aframe-physics-system.js:14526:13
    at aframe-physics-system.js:14604:5
    at exports.createBoxShape (aframe-physics-system.js:13927:7)
    at exports.createCollisionShapes (aframe-physics-system.js:13893:20)
    at n._createCollisionShape (aframe-physics-system.js:16439:41)
    at AmmoBody._updateShapes (aframe-physics-system.js:16402:18)
    at n.beforeStep (aframe-physics-system.js:16568:10)
    at i.tick (aframe-physics-system.js:18808:36)
    at v.tick (a-scene.js:703:36)
    at v.render (a-scene.js:743:32)

**Comment by InfiniteLee** [comment]
Done!
